#!/usr/bin/env nu
# gen_inventory.nu — read data/crypto_raw.csv, classify symbols by source file,
# write docs/inventory.md. Run this after parse_crypto.nu populates the CSV.
#
# Classification is the only human-judgment layer: a table mapping source file
# path fragments to family names. Any file not in the table produces an
# "Unclassified" section so new additions are never silently dropped.
#
# Usage:
#   nu scripts/gen_inventory.nu
#   nu scripts/gen_inventory.nu --csv other/path.csv

def main [--csv: string = "data/crypto_raw.csv"] {
    let out = "docs/inventory.md"

    if not ($csv | path exists) {
        error make {msg: $"CSV not found: ($csv) — run parse_crypto.nu first"}
    }

    let raw = open $csv

    # ── 1. top-level exports from crypto.zig at indent 0 ──────────────────────
    let top = ($raw
        | where file == "crypto.zig" and indent == 0
        | sort-by line)

    print $"  top-level exports in crypto.zig: ($top | length)"

    # ── 2. classification table ────────────────────────────────────────────────
    # Maps a substring of the *source file path* to a family.
    # Order matters: first match wins.
    let families = [
        # Stream ciphers
        {frag: "chacha20.zig",         family: "Stream ciphers"}
        {frag: "salsa20.zig",          family: "Stream ciphers"}
        # AEAD (higher-level chacha_poly / aegis / ascon / aes ccm etc.)
        {frag: "aead/chacha_poly",     family: "AEAD"}
        {frag: "aegis",                family: "AEAD"}
        {frag: "ascon.zig",            family: "AEAD"}
        {frag: "aes_gcm",              family: "AEAD"}
        {frag: "aes_ocb",              family: "AEAD"}
        {frag: "aes_siv",              family: "AEAD"}
        {frag: "aes_ccm",              family: "AEAD"}
        {frag: "isap",                 family: "AEAD"}
        # Hashing — top-level only (Blake3, KT128/256, AsconHash, Md5, Sha1)
        {frag: "blake3.zig",           family: "Hashing"}
        {frag: "KangarooTwelve",       family: "Hashing"}
        {frag: "sha1",                 family: "Hashing"}
        {frag: "md5",                  family: "Hashing"}
        # MACs
        {frag: "poly1305.zig",         family: "MACs"}
        {frag: "ghash_polyval",        family: "MACs"}
        {frag: "cbc_mac",              family: "MACs"}
        {frag: "cmac",                 family: "MACs"}
        # KDF
        {frag: "hkdf",                 family: "KDF"}
        # Key exchange / curves
        {frag: "25519",                family: "Key exchange / curves"}
        {frag: "pcurves",              family: "Key exchange / curves"}
        {frag: "nacl",                 family: "Key exchange / curves"}
        # Signatures
        {frag: "ecdsa",                family: "Signatures"}
        {frag: "mldsa",                family: "Signatures"}
        {frag: "rsa",                  family: "Signatures"}
        # Post-quantum KEM
        {frag: "ml_kem",               family: "Post-quantum KEM"}
        {frag: "hybrid",               family: "Post-quantum KEM"}
        # Password hashing
        {frag: "pwhash",               family: "Password hashing"}
        {frag: "argon2",               family: "Password hashing"}
        # Errors
        {frag: "errors",               family: "Error types"}
        # Config / utilities
        {frag: "SideChannelsMitigations", family: "Configuration"}
        {frag: "Certificate",          family: "Configuration"}
    ]

    # ── 3. resolve source file for each export ─────────────────────────────────
    # If sig contains @import("..."), pull the inner path.
    # Otherwise the symbol is defined inline in crypto.zig (e.g. error types).
    def source_file [sig: string, name: string] {
        let m = ($sig | parse --regex '@import\("(?P<path>[^"]+)"')
        if ($m | is-not-empty) {
            $m | get path | first
        } else {
            # inline in crypto.zig — use name as a hint
            $name
        }
    }

    # ── 4. classify each symbol ────────────────────────────────────────────────
    let classified = ($top | each {|row|
        let src    = (source_file $row.signature $row.name)
        let family = (
            $families
            | where {|f| $src | str contains $f.frag}
            | get family?
            | get 0?
            | default "Unclassified"
        )
        $row | insert src_file $src | insert family $family
    })

    # ── 5. build markdown ──────────────────────────────────────────────────────
    let date     = (date now | format date "%Y-%m-%d")
    let total    = ($classified | length)
    let families_found = ($classified | get family | uniq | sort)

    mut lines = [
        "# std.crypto inventory — Zig 0.16"
        ""
        $"Generated by `scripts/gen_inventory.nu` from `data/crypto_raw.csv`."
        $"Source: `/usr/lib/zig/std/crypto.zig` \(Zig 0.16\), generated ($date)."
        "Edit `scripts/gen_inventory.nu` (the classification table) to change groupings."
        "Never edit this file directly — regenerate with `nu scripts/gen_inventory.nu`."
        ""
        $"**($total) top-level exports** \(indent=0\) in the crypto namespace."
        ""
        "---"
        ""
    ]

    # a section per family (deterministic order)
    let family_order = [
        "AEAD"
        "Stream ciphers"
        "Hashing"
        "MACs"
        "KDF"
        "Password hashing"
        "Key exchange / curves"
        "Signatures"
        "Post-quantum KEM"
        "Error types"
        "Configuration"
        "Unclassified"
    ]

    for fam in $family_order {
        let members = ($classified | where family == $fam | sort-by name)
        if ($members | is-empty) { continue }

        $lines = ($lines | append [
            $"## ($fam)"
            ""
            "| name | kind | source | doc |"
            "|---|---|---|---|"
        ])

        for row in $members {
            let doc  = if ($row.doc | str length) > 0 { $row.doc } else { "—" }
            let kind = $row.kind
            let src  = ($row.src_file | str replace -r '^crypto/' '' | str replace -r '\.zig$' '')
            $lines = ($lines | append $"| `($row.name)` | ($kind) | ($src) | ($doc) |")
        }

        $lines = ($lines | append ["" "---" ""])
    }

    # summary table
    $lines = ($lines | append [
        "## Summary"
        ""
        "| family | count |"
        "|---|---|"
    ])
    for fam in $family_order {
        let n = ($classified | where family == $fam | length)
        if $n > 0 {
            $lines = ($lines | append $"| ($fam) | ($n) |")
        }
    }

    let unclassified = ($classified | where family == "Unclassified")
    if ($unclassified | is-not-empty) {
        print $"\nWARNING: ($unclassified | length) unclassified entries:"
        for r in $unclassified {
            print $"  ($r.name)  →  ($r.src_file)"
        }
        print "  Add these source file fragments to the `families` table in gen_inventory.nu"
    }

    $lines | str join "\n" | save -f $out
    print $"\ninventory written → ($out)  \(($total) entries)"
}
