#!/usr/bin/env nu
# build_tree.nu — run the structural mapper (src/maptree.zig), save the flat map,
# nest it into a JSON tree, and report first-pass anomalies. No interpretation.
#
# Query the flat map natively, e.g.:
#   open data/crypto_tree.tsv | sort-by n_decls -r | first 10
#   open data/crypto_tree.tsv | where n_fns == 0 and n_types > 0   # pure namespaces

# Build one node + its direct children, recursively, from the flat rows.
def build-node [path: string, rows: table] {
    let me = ($rows | where path == $path | first)
    let prefix = $"($path)."
    let plen = ($prefix | str length)
    let kids = ($rows | where {|r| ($r.path | str starts-with $prefix) and (not ($r.path | str substring $plen.. | str contains ".")) })
    mut children = {}
    for k in $kids {
        let name = ($k.path | split row "." | last)
        $children = ($children | insert $name (build-node $k.path $rows))
    }
    {
        kind: $me.kind, n_decls: $me.n_decls, n_fields: $me.n_fields,
        n_types: $me.n_types, n_fns: $me.n_fns, n_consts: $me.n_consts,
        children: $children,
    }
}

# render a node + descendants to indented text lines, up to maxd
def render-node [name: string, node: record, depth: int, maxd: int] {
    let tag = (if $node.kind != "struct" { $" [($node.kind)]" } else { "" })
    let fld = (if $node.n_fields > 0 { $" fld($node.n_fields)" } else { "" })
    let indent = (0..<$depth | each { "  " } | str join "")
    mut lines = [($"($indent)($name)  d($node.n_decls) t($node.n_types) f($node.n_fns) c($node.n_consts)($fld)($tag)")]
    let kids = ($node.children | columns)
    if $depth >= $maxd {
        if ($kids | length) > 0 {
            $lines = ($lines | append $"($indent)  … ($kids | length) sub-containers")
        }
        return $lines
    }
    for cn in $kids {
        $lines = ($lines | append (render-node $cn ($node.children | get $cn) ($depth + 1) $maxd))
    }
    $lines
}

def main [] {
    let raw = (^zig run src/maptree.zig | into string)
    mkdir data
    $raw | save -f data/crypto_tree.tsv
    let rows = ($raw | from tsv)        # counts infer as int, path/kind as string
    print $"crypto_tree.tsv written → ($rows | length) containers"

    let tree = { crypto: (build-node "crypto" $rows) }
    $tree | to json | save -f data/crypto_tree.json
    print "crypto_tree.json written"

    # human-readable indented map (depth ≤ 2)
    let header = "# std.crypto — structural map (Zig 0.16)

Faithful container tree from `src/maptree.zig` (compiler reflection). Counts are
exact: `d`=direct decls, `t`=sub-types, `f`=functions, `c`=consts, `fld`=fields.
No interpretation — structure only. Generated by `scripts/build_tree.nu`.
Depth shown ≤ 2; full tree in `data/crypto_tree.json`. Not descended (protocol/
encoding plumbing that breaks reflection): codecs, tls, Certificate.

```"
    let body = (render-node "crypto" ($tree | get crypto) 0 2 | str join "\n")
    [$header $body "```"] | str join "\n" | save -f docs/structure.md
    print "docs/structure.md written"

    print $"\n=== totals ==="
    print $"  containers: ($rows | length)   total decls: ($rows | get n_decls | math sum)"
    print ($rows | group-by kind | items {|k, v| {kind: $k, n: ($v | length)} })

    print $"\n=== widest containers \(most direct decls\) ==="
    print ($rows | sort-by n_decls -r | first 10 | select path n_decls n_types n_fns n_consts)

    print $"\n=== data-only containers \(fields, no decls\) ==="
    print ($rows | where n_fields > 0 and n_decls == 0 | select path kind n_fields | sort-by path)

    print $"\n=== functions living directly in a namespace ==="
    print ($rows | where n_fns > 0 and n_types > 0 and depth <= 1 | select path n_fns n_types n_consts)

    print $"\n=== deepest paths ==="
    print ($rows | sort-by depth -r | first 8 | select depth path)
}
