#!/usr/bin/env nu
# build_surface.nu — run src/surface.zig (reflection over the dev-facing namespaces)
# and group the result by family. Answers: what does a developer actually reach for?
#
# Classes:
#   PRIMITIVE — a type you instantiate/call (Sha256, ChaCha20Poly1305, Ed25519, Box)
#   free-fn   — a free function you call (pbkdf2, timingSafeEql)
#   BUILDER   — generic `fn(...) type` the primitives are aliases of (middle layer)
#   namespace — organisational container you navigate through
# The math/hardware/protocol layer is not walked — it isn't part of the surface.
#
# Outputs: data/surface.tsv + docs/surface.md

def main [] {
    let raw = (^zig run src/surface.zig | into string)
    $raw | save -f data/surface.tsv
    let rows = ($raw | from tsv | insert family {|r| $r.path | split row "." | first })

    print "surface by class:"
    print ($rows | group-by class | items {|k, v| {class: $k, n: ($v | length)} } | sort-by n -r)

    # dev-facing = what you instantiate or call
    let prims = ($rows | where class == "PRIMITIVE")
    let builders = ($rows | where class == "BUILDER")
    let freefns = ($rows | where class == "free-fn")

    let by_family = ($prims | group-by family | items {|fam, items|
        {
            family: $fam,
            primitives: ($items | length),
            builders: ($builders | where family == $fam | length),
            free_fns: ($freefns | where family == $fam | length),
        }
    } | sort-by primitives -r)
    print "\ndev-facing primitives by family:"
    print $by_family

    # markdown report
    mut md = [
        "# std.crypto — the developer-facing surface"
        ""
        "What a developer actually reaches for, identified from the structural map by"
        "reflection over the public namespaces (`src/surface.zig`). The math / hardware /"
        "protocol machinery is deliberately excluded — it is not part of the surface."
        ""
        "- **PRIMITIVE** — a type you instantiate or call directly"
        "- **free-fn** — a free function you call (not a method)"
        "- **BUILDER** — a generic `fn(...) type` the primitives are aliases of (middle layer)"
        ""
        "## Counts by family"
        ""
        "| family | primitives | builders | free-fns |"
        "|---|--:|--:|--:|"
    ]
    for r in $by_family {
        $md = ($md | append $"| ($r.family) | ($r.primitives) | ($r.builders) | ($r.free_fns) |")
    }
    $md = ($md | append ["" "## Primitives by family" ""])
    for fam in ($by_family | get family) {
        let names = ($prims | where family == $fam | get name | sort | str join ", ")
        $md = ($md | append [$"### ($fam)" "" $names ""])
    }
    let ff = ($freefns | each {|r| $"`($r.path).($r.name)`" } | str join ", ")
    $md = ($md | append ["## Free functions" "" $ff ""])
    $md = ($md | append "*Generated by `scripts/build_surface.nu` from `src/surface.zig` (Zig 0.16, 2026-06-17).*")
    $md | str join "\n" | save -f docs/surface.md
    print "\ndocs/surface.md written"
}
